=== iivanoo/winknocks/KnockerEclipseProject/xSchemas/KnockSequence.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="KnockSequence">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="smokePackets">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="min" type="xs:nonNegativeInteger"/>
						<xs:element name="max" type="xs:nonNegativeInteger"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="maxFakePayload" type="xs:nonNegativeInteger"/>
			<xs:element name="actions">
				<xs:complexType>
					<xs:choice maxOccurs="unbounded">
						<xs:element name="openPort" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="portNumber">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="65535"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="exclusive" type="xs:boolean"/>
									<xs:element name="wait" type="xs:nonNegativeInteger" minOccurs="0"/>
									<xs:element name="timeout" type="xs:nonNegativeInteger" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="closePort" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="portNumber">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="65535"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="wait" type="xs:nonNegativeInteger" minOccurs="0"/>
									<xs:element name="timeout" type="xs:nonNegativeInteger" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="executeScript" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="script" type="xs:string"/>
									<xs:element name="wait" type="xs:nonNegativeInteger" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="packets">
				<xs:complexType>
					<xs:choice maxOccurs="unbounded">
						<xs:element name="UDPpacket" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="srcPortNumber">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="65535"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="dstPortNumber">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="65535"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="payload" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="TCPpacket" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="srcPortNumber">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="65535"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="dstPortNumber">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="65535"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="sequenceNumber" type="xs:nonNegativeInteger"/>
									<xs:element name="ackNumber" type="xs:nonNegativeInteger"/>
									<xs:element name="windowSize" type="xs:nonNegativeInteger"/>
									<xs:element name="flags">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="ack">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="0"/>
															<xs:maxInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:element>
												<xs:element name="syn">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="0"/>
															<xs:maxInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:element>
												<xs:element name="fin">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="0"/>
															<xs:maxInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:element>
												<xs:element name="push">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="0"/>
															<xs:maxInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:element>
												<xs:element name="reset">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="0"/>
															<xs:maxInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:element>
												<xs:element name="urgent">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="0"/>
															<xs:maxInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="payload" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="ICMPpacket" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="type" type="xs:nonNegativeInteger"/>
									<xs:element name="code" type="xs:nonNegativeInteger"/>
									<xs:element name="data" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			
		</xs:sequence>
	</xs:complexType>
</xs:element>



</xs:schema>

=== iivanoo/winknocks/ListenerEclipseProject/knockSequences/newSequence1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<KnockSequence  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="KnockSequence.xsd">
	<id>2</id>
	<description>description of the knock sequence</description>
	<smokePackets>
		<min>0</min>
		<max>0</max>
	</smokePackets>
	<maxFakePayload>100</maxFakePayload>
	<actions>

		<closePort>
			<portNumber>4000</portNumber>
			<wait>0</wait>
			<timeout>0</timeout>
		</closePort>
		<!-- put here the actions to be executed server-side -->

	</actions>

	<packets>
		<!-- put here the packets of the knock sequence -->

	</packets>
</KnockSequence>

=== iivanoo/winknocks/ListenerEclipseProject/knockSequences/newSequence3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<KnockSequence  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="KnockSequence.xsd">
	<id>3</id>
	<description>description of the knock sequence</description>
	<smokePackets>
		<min>2</min>
		<max>20</max>
	</smokePackets>
	<maxFakePayload>100</maxFakePayload>
	<actions>

		<!-- put here the actions to be executed server-side -->

	</actions>

	<packets>

		<ICMPpacket>
			<type>8</type>
			<code>0</code>
			<data></data>
		</ICMPpacket>

<!-- put here the packets of the knock sequence -->

	</packets>
</KnockSequence>

=== iivanoo/winknocks/KnockerEclipseProject/knockSequences/IvanoProva.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<KnockSequence  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="KnockSequence.xsd">
	<id>8</id>
	<description>tutto ok</description>
	<smokePackets>
		<min>2</min>
		<max>33</max>
	</smokePackets>
	<maxFakePayload>2200</maxFakePayload>
	<actions>

		<openPort>
			<portNumber>4000</portNumber>
			<exclusive>true</exclusive>
			<wait>12</wait>
			<timeout>0</timeout>
		</openPort>

	</actions>
	
	<packets>
		<UDPpacket>
			<srcPortNumber>7000</srcPortNumber>
			<dstPortNumber>3000</dstPortNumber>
			<payload>ciao</payload>
		</UDPpacket>
		<UDPpacket>
			<srcPortNumber>7000</srcPortNumber>
			<dstPortNumber>3000</dstPortNumber>
			<payload>ciao</payload>
		</UDPpacket>

		<TCPpacket>
			<srcPortNumber>8000</srcPortNumber>
			<dstPortNumber>9000</dstPortNumber>
			<sequenceNumber>1</sequenceNumber>
			<ackNumber>2</ackNumber>
			<windowSize>50</windowSize>
			<flags>
				<ack>0</ack>
				<syn>1</syn>
				<fin>0</fin>
				<push>0</push>
				<reset>0</reset>
				<urgent>0</urgent>
			</flags>
			<payload>payload</payload>
		</TCPpacket>
		<TCPpacket>
			<srcPortNumber>5000</srcPortNumber>
			<dstPortNumber>4000</dstPortNumber>
			<sequenceNumber>3</sequenceNumber>
			<ackNumber>4</ackNumber>
			<windowSize>500</windowSize>
			<flags>
				<ack>0</ack>
				<syn>0</syn>
				<fin>0</fin>
				<push>1</push>
				<reset>0</reset>
				<urgent>0</urgent>
			</flags>
			<payload>ciao</payload>
		</TCPpacket>
		<ICMPpacket>
			<type>8</type>
			<code>1</code>
			<data>ciaociaociao</data>
		</ICMPpacket>
	</packets>
</KnockSequence>

=== iivanoo/winknocks/ListenerEclipseProject/knockSequences/aaa.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<KnockSequence  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="KnockSequence.xsd">
	<id>10</id>
	<description>tutto ok</description>
	<smokePackets>
		<min>2</min>
		<max>5</max>
	</smokePackets>
	<maxFakePayload>3</maxFakePayload>
	<actions>
		<closePort>
			<portNumber>30000</portNumber>
			<timeout>3000</timeout>
		</closePort>
		<openPort>
			<portNumber>2500</portNumber>
			<exclusive>false</exclusive>
			<wait>0</wait>
			<timeout>60</timeout>
		</openPort>
		<openPort>
			<portNumber>2000</portNumber>
			<exclusive>true</exclusive>
			<wait>0</wait>
			<timeout>3000</timeout>
		</openPort>
		<executeScript>
			<script>c:\programmi\mirc\mirc.exe</script>
		</executeScript>
	</actions>
	
	<packets>
		<UDPpacket>
			<srcPortNumber>7000</srcPortNumber>
			<dstPortNumber>3000</dstPortNumber>
			<payload>ciao</payload>
		</UDPpacket>
		<TCPpacket>
			<srcPortNumber>5000</srcPortNumber>
			<dstPortNumber>4000</dstPortNumber>
			<sequenceNumber>3</sequenceNumber>
			<ackNumber>4</ackNumber>
			<windowSize>500</windowSize>
			<flags>
				<ack>0</ack>
				<syn>1</syn>
				<fin>0</fin>
				<push>0</push>
				<reset>0</reset>
				<urgent>0</urgent>
			</flags>
			<payload>ciaoCIAO</payload>
		</TCPpacket>

	</packets>
</KnockSequence>

=== iivanoo/winknocks/KnockerEclipseProject/knockSequences/newSeq.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<KnockSequence  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="KnockSequence.xsd">
	<id>0</id>
	<description>description of the knock sequence</description>
	<smokePackets>
		<min>2</min>
		<max>20</max>
	</smokePackets>
	<maxFakePayload>100</maxFakePayload>
	<actions>

		<openPort>
			<portNumber>3000</portNumber>
			<exclusive>true</exclusive>
			<wait>10</wait>
			<timeout>30</timeout>
		</openPort>
		<!-- put here the actions to be executed server-side -->

	</actions>

	<packets>

		<UDPpacket>
			<srcPortNumber>7000</srcPortNumber>
			<dstPortNumber>3000</dstPortNumber>
			<payload>AAA</payload>
		</UDPpacket>
		<UDPpacket>
			<srcPortNumber>22000</srcPortNumber>
			<dstPortNumber>33000</dstPortNumber>
			<payload>payloadpayload</payload>
		</UDPpacket>
		<!-- put here the packets of the knock sequence -->

	</packets>
</KnockSequence>

=== iivanoo/winknocks/KnockerEclipseProject/knockSequences/newSeqf.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<KnockSequence  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="KnockSequence.xsd">
	<id>4</id>
	<description>description of the knock sequence</description>
	<smokePackets>
		<min>2</min>
		<max>20</max>
	</smokePackets>
	<maxFakePayload>100</maxFakePayload>
	<actions>

		<!-- put here the actions to be executed server-side -->

	</actions>

	<packets>

		<TCPpacket>
			<srcPortNumber>7000</srcPortNumber>
			<dstPortNumber>3000</dstPortNumber>
			<sequenceNumber>1</sequenceNumber>
			<ackNumber>2</ackNumber>
			<windowSize>50</windowSize>
			<flags>
				<ack>0</ack>
				<syn>1</syn>
				<fin>0</fin>
				<push>0</push>
				<reset>0</reset>
				<urgent>0</urgent>
			</flags>
			<payload>payload</payload>
		</TCPpacket>
		<!-- put here the packets of the knock sequence -->

	</packets>
</KnockSequence>
